CREATE TABLE "message_templates" ("id" TEXT PRIMARY KEY,"organization_id" TEXT NOT NULL,"name" TEXT NOT NULL,"purpose" TEXT NOT NULL,"subject" TEXT NOT NULL,"body" TEXT NOT NULL,"version" INTEGER NOT NULL DEFAULT 1,"created_by_id" TEXT NOT NULL,"created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE "outreach_threads" ("id" TEXT PRIMARY KEY,"organization_id" TEXT NOT NULL,"candidate_id" TEXT NOT NULL REFERENCES "candidates"("id"),"application_id" TEXT,"position_id" TEXT,"purpose" TEXT NOT NULL,"status" TEXT NOT NULL DEFAULT 'draft',"requested_fields" JSON NOT NULL DEFAULT '[]',"created_by_id" TEXT NOT NULL,"created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,"updated_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE "outreach_messages" ("id" TEXT PRIMARY KEY,"organization_id" TEXT NOT NULL,"thread_id" TEXT NOT NULL REFERENCES "outreach_threads"("id"),"direction" TEXT NOT NULL,"subject" TEXT NOT NULL,"body" TEXT NOT NULL,"status" TEXT NOT NULL DEFAULT 'draft',"approval_version" INTEGER NOT NULL DEFAULT 0,"approved_by_id" TEXT,"approved_at" TIMESTAMP,"provider" TEXT,"provider_message_id" TEXT,"idempotency_key" TEXT NOT NULL UNIQUE,"sent_at" TIMESTAMP,"created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,"updated_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE "candidate_responses" ("id" TEXT PRIMARY KEY,"organization_id" TEXT NOT NULL,"thread_id" TEXT NOT NULL REFERENCES "outreach_threads"("id"),"provider_event_id" TEXT NOT NULL,"body" TEXT NOT NULL,"parsed_suggestions" JSON NOT NULL DEFAULT '[]',"received_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,UNIQUE("organization_id","provider_event_id"));
CREATE TABLE "delivery_events" ("id" TEXT PRIMARY KEY,"organization_id" TEXT NOT NULL,"thread_id" TEXT NOT NULL REFERENCES "outreach_threads"("id"),"message_id" TEXT,"provider_event_id" TEXT NOT NULL,"event_type" TEXT NOT NULL,"metadata" JSON NOT NULL DEFAULT '{}',"created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,UNIQUE("organization_id","provider_event_id"));
CREATE TABLE "opt_outs" ("id" TEXT PRIMARY KEY,"organization_id" TEXT NOT NULL,"candidate_id" TEXT NOT NULL REFERENCES "candidates"("id"),"thread_id" TEXT,"channel" TEXT NOT NULL,"reason" TEXT,"recorded_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,UNIQUE("organization_id","candidate_id","channel"));
CREATE INDEX "message_templates_org_purpose_idx" ON "message_templates"("organization_id","purpose");
CREATE INDEX "outreach_threads_org_candidate_idx" ON "outreach_threads"("organization_id","candidate_id","updated_at");
CREATE INDEX "outreach_messages_org_thread_idx" ON "outreach_messages"("organization_id","thread_id","created_at");
