import { notFound } from 'next/navigation';
import Link from 'next/link';
import { AppShell, CandidateAvatar } from '@/components/recruiting/app-shell';
import { Icon } from '@/components/recruiting/icons';
import { recruitingService } from '@/features/sorted/services/recruiting-service';

export default async function PositionDetailPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params; const [position, candidates] = await Promise.all([recruitingService.getPosition(id), recruitingService.listCandidates()]); if (!position) notFound();
  const assigned = candidates.filter((candidate) => candidate.positionId === position.id);
  return <AppShell active="positions"><div className="detail-title"><Link href="/positions">← Positions</Link><div className="page-header"><div><span className={`status ${position.status}`}>{position.status.replace('_', ' ')}</span><h1>{position.title}</h1><p>{position.location} · {position.employmentType}</p></div><button className="button secondary">Edit position</button></div></div><div className="tabs"><span className="active">Overview</span><span>Candidates {assigned.length}</span><span>Evaluation rubric</span><span>Hiring panel</span></div><div className="detail-grid"><section className="surface"><div className="section-heading"><h2>Candidate pipeline</h2><Link href="/candidates">Open candidate list</Link></div>{assigned.map((candidate, index) => <Link className="candidate-row" href={`/candidates/${candidate.id}`} key={candidate.id}><CandidateAvatar initials={candidate.initials} index={index}/><div className="candidate-main"><h3>{candidate.name}</h3><p>{candidate.headline}</p></div><span className="score"><strong>{candidate.roleFit}</strong><small>role fit</small></span><span className="stage">{candidate.stage.replace('_', ' ')}</span><Icon name="arrow" size={15}/></Link>)}{assigned.length === 0 && <div className="empty-state"><Icon name="users" size={28}/><h3>No candidates yet</h3><p>Import candidates into this position when you’re ready.</p></div>}</section><aside className="surface overview-panel"><span className="eyebrow">EVALUATION</span><h2>{position.status === 'screening' ? 'Rubric approved' : 'Rubric needs attention'}</h2><p>{position.status === 'screening' ? 'Candidates are evaluated only against this approved position rubric.' : 'Screening stays paused until a hiring manager approves the rubric.'}</p><div className="rubric-item"><span>Backend architecture</span><strong>30%</strong></div><div className="rubric-item"><span>Distributed systems</span><strong>25%</strong></div><div className="rubric-item"><span>Technical leadership</span><strong>20%</strong></div><div className="rubric-item"><span>Logistics</span><strong>25%</strong></div><small className="simulation-label">Demo rubric · no Sarvam call made</small></aside></div></AppShell>;
}

