'use server';
import { revalidatePath } from 'next/cache';
import { requireCurrentAccess } from '@/lib/auth/session';
import { CandidateIngestionRepository } from '@/features/candidates/repositories/candidate-ingestion-repository';
import { validateCandidateDocument } from '@/features/candidates/services/document-validation';
import { privateDocumentStorage } from '@/features/candidates/services/private-document-storage';
import { enqueueJob } from '@/lib/worker';
import { queue } from '@/lib/queue/postgres-queue';
import { processCandidateDocument } from '@/workers/tasks/extract-cv-document';
import { EvidenceClaimInputSchema, EvidenceReviewInputSchema } from '@/features/candidates/schemas/evidence-profile';
import { EvidenceProfileRepository } from '@/features/candidates/repositories/evidence-profile-repository';
import { MatchCandidateInputSchema, validateCriterionCoverage } from '@/features/evaluations/schemas/evaluation';
import { EvaluationRepository } from '@/features/evaluations/repositories/evaluation-repository';
import { evaluateCriteria } from '@/features/evaluations/sarvam/criterion-evaluation-provider';
import { CandidatePrivacyRequestInputSchema, CandidatePrivacyDecisionInputSchema } from '@/features/candidates/schemas/privacy';
import { CandidatePrivacyRepository } from '@/features/candidates/repositories/candidate-privacy-repository';
import { privateCandidateAudioStorage } from '@/features/outreach/services/private-candidate-audio-storage';
import { getMalwareScanner } from '@/features/candidates/services/malware-scanner';
import { enforceRateLimit } from '@/lib/security/rate-limit';

async function scanAndQueueDocument(input:{repo:CandidateIngestionRepository;organizationId:string;documentId:string;actorId:string;checksum:string}){
  const row=await input.repo.getDocument(input.organizationId,input.documentId);if(!row)throw new Error('Organization-scoped candidate document not found.');
  const bytes=await privateDocumentStorage.get(String(row.storage_key));const scan=await getMalwareScanner().scan(bytes);
  const status=scan.verdict==='clean'?(scan.simulated?'clean_simulated':'clean'):scan.verdict==='infected'?'quarantined':'scan_failed';
  await input.repo.recordMalwareScan({org:input.organizationId,documentId:input.documentId,actorId:input.actorId,status,provider:scan.provider,engineVersion:scan.engineVersion,requestId:scan.requestId,error:scan.verdict==='infected'?`Threat detected: ${scan.threatName}`:scan.verdict==='error'?scan.normalizedError:undefined});
  if(scan.verdict!=='clean')return false;
  const job=await enqueueJob('extract-cv-document',{organizationId:input.organizationId,documentId:input.documentId},{jobKey:`extract-cv:${input.organizationId}:${input.checksum}`,queue:'candidate-ingestion',maxAttempts:3});if((process.env.DATABASE_URL??'file:').startsWith('file:')){await processCandidateDocument({organizationId:input.organizationId,documentId:input.documentId});await queue.completeJob(job.id)}return true;
}

export type ImportState={error?:string;message?:string;skipped?:string[]};
export async function importCandidates(_state:ImportState,formData:FormData):Promise<ImportState>{
 try{const access=await requireCurrentAccess('candidates:manage');await enforceRateLimit(access.organization.id,access.userId,'candidate_upload');const files=formData.getAll('files').filter((v):v is File=>v instanceof File&&v.size>0);if(!files.length||files.length>20)return {error:'Choose between 1 and 20 PDF or DOCX CVs.'};const positionValue=String(formData.get('positionId')??'');const positionId=positionValue||undefined;const repo=new CandidateIngestionRepository();const accepted:{file:File;bytes:Uint8Array;checksum:string;mediaType:string}[]=[];const skipped:string[]=[];
  for(const file of files){const bytes=new Uint8Array(await file.arrayBuffer());const valid=validateCandidateDocument(file,bytes);const duplicate=await repo.checksumExists(access.organization.id,valid.checksum);if(duplicate){skipped.push(`${file.name} already belongs to ${duplicate.display_name}.`);continue}accepted.push({file,bytes,checksum:valid.checksum,mediaType:valid.mediaType})}
  if(!accepted.length)return {error:'No new documents were imported.',skipped};const runId=crypto.randomUUID();await repo.createRun({id:runId,organizationId:access.organization.id,positionId,count:accepted.length,actorId:access.userId,auditId:crypto.randomUUID()});
  let processing=0;for(const item of accepted){const sourceId=crypto.randomUUID(),documentId=crypto.randomUUID(),storageKey=`${access.organization.id}/${documentId}`;await privateDocumentStorage.put(storageKey,item.bytes);await repo.createDocument({organizationId:access.organization.id,runId,sourceId,documentId,storageKey,filename:item.file.name,mediaType:item.mediaType,byteSize:item.file.size,checksum:item.checksum,actorId:access.userId});if(await scanAndQueueDocument({repo,organizationId:access.organization.id,documentId,actorId:access.userId,checksum:item.checksum}))processing++}
  revalidatePath('/candidates');return {message:`Secured ${accepted.length} upload${accepted.length===1?'':'s'}. ${processing} cleared for processing; ${accepted.length-processing} isolated for review.`,skipped};
 }catch(error){return {error:error instanceof Error?error.message:'Candidate import failed.'}}
}
export async function retryDocumentSecurityScan(formData:FormData){const access=await requireCurrentAccess('candidates:manage');const documentId=String(formData.get('documentId'));if(!/^[0-9a-f-]{36}$/i.test(documentId))throw new Error('Invalid document.');const repo=new CandidateIngestionRepository();const row=await repo.getDocument(access.organization.id,documentId);if(!row||!['quarantined','scan_failed'].includes(String(row.malware_scan_status)))throw new Error('Document is not eligible for a security rescan.');await scanAndQueueDocument({repo,organizationId:access.organization.id,documentId,actorId:access.userId,checksum:String(row.checksum)});revalidatePath('/candidates')}
export async function mergeDuplicate(formData:FormData){const access=await requireCurrentAccess('candidates:manage');await new CandidateIngestionRepository().merge(access.organization.id,String(formData.get('reviewId')),access.userId);revalidatePath('/candidates')}
export async function undoMerge(formData:FormData){const access=await requireCurrentAccess('candidates:manage');await new CandidateIngestionRepository().split(access.organization.id,String(formData.get('candidateId')),access.userId);revalidatePath('/candidates')}
export async function addExternalSource(formData:FormData){const access=await requireCurrentAccess('candidates:manage');const provider=String(formData.get('provider'));const url=String(formData.get('url'));if(!['github','portfolio','linkedin'].includes(provider))throw new Error('Unsupported source type.');const parsed=new URL(url);if(!['http:','https:'].includes(parsed.protocol))throw new Error('Use an HTTPS profile URL.');await new CandidateIngestionRepository().addExternalSource({org:access.organization.id,candidateId:String(formData.get('candidateId')),actor:access.userId,provider,url:parsed.toString()});revalidatePath(`/candidates/${String(formData.get('candidateId'))}`)}
export async function addEvidenceClaim(formData:FormData){const access=await requireCurrentAccess('candidates:manage');const parsed=EvidenceClaimInputSchema.parse({candidateId:formData.get('candidateId'),claimType:formData.get('claimType'),label:formData.get('label'),value:formData.get('value'),status:'explicit',sourceId:formData.get('sourceId')||undefined,pageNumber:formData.get('pageNumber')||undefined,section:formData.get('section')||undefined,excerpt:formData.get('excerpt')||undefined,confidence:1});await new EvidenceProfileRepository().addClaim(access.organization.id,access.userId,parsed);revalidatePath(`/candidates/${parsed.candidateId}`)}
export async function reviewEvidenceClaim(formData:FormData){const access=await requireCurrentAccess('candidates:manage');const parsed=EvidenceReviewInputSchema.parse({candidateId:formData.get('candidateId'),claimId:formData.get('claimId'),action:formData.get('action'),correctedValue:formData.get('correctedValue')||undefined,reason:formData.get('reason')});await new EvidenceProfileRepository().reviewClaim(access.organization.id,access.userId,parsed);revalidatePath(`/candidates/${parsed.candidateId}`)}
export async function matchCandidate(formData:FormData){const access=await requireCurrentAccess('candidates:manage');await enforceRateLimit(access.organization.id,access.userId,'candidate_match');const parsed=MatchCandidateInputSchema.parse({candidateId:formData.get('candidateId'),positionId:formData.get('positionId')});const repo=new EvaluationRepository();const context=await repo.context(access.organization.id,parsed.candidateId,parsed.positionId);const result=await evaluateCriteria(context.criteria,context.claims);const judgments=validateCriterionCoverage(context.criteria.map(c=>c.id),result.data.judgments);await repo.save({organizationId:access.organization.id,actorId:access.userId,...parsed,...context,judgments,execution:result.execution});revalidatePath('/candidates');revalidatePath(`/candidates/${parsed.candidateId}`)}
export async function createCandidatePrivacyRequest(formData:FormData){const access=await requireCurrentAccess('candidates:manage');const parsed=CandidatePrivacyRequestInputSchema.parse({candidateId:formData.get('candidateId'),requestType:formData.get('requestType'),details:formData.get('details')});await new CandidatePrivacyRepository().request(access.organization.id,access.userId,parsed);revalidatePath(`/candidates/${parsed.candidateId}`)}
export async function decideCandidatePrivacyRequest(formData:FormData){const access=await requireCurrentAccess('organization:manage');const parsed=CandidatePrivacyDecisionInputSchema.parse({candidateId:formData.get('candidateId'),requestId:formData.get('requestId'),decision:formData.get('decision'),rationale:formData.get('rationale')});const keys=await new CandidatePrivacyRepository().decide(access.organization.id,access.userId,parsed);for(const key of keys.documentKeys)await privateDocumentStorage.delete(key);for(const key of keys.audioKeys)await privateCandidateAudioStorage.remove(key);revalidatePath('/candidates');revalidatePath(`/candidates/${parsed.candidateId}`)}
export type PrivacyLinkState={url?:string;error?:string};
export async function createCandidatePrivacyLink(_state:PrivacyLinkState,formData:FormData):Promise<PrivacyLinkState>{try{const access=await requireCurrentAccess('candidates:manage');const candidateId=String(formData.get('candidateId'));if(!/^[0-9a-f-]{36}$/i.test(candidateId))return{error:'Invalid candidate.'};const token=await new CandidatePrivacyRepository().createHostedAccess(access.organization.id,access.userId,candidateId);const base=(process.env.APP_URL||'http://localhost:7070').replace(/\/$/,'');return{url:`${base}/privacy/${token}`}}catch(error){return{error:error instanceof Error?error.message:'Could not create a privacy link.'}}}
