import { executeQuery } from "@/lib/db";
import { nextBusinessHour } from "../schemas/outreach";
import { queue } from "@/lib/queue/postgres-queue";
import { getEmailProvider } from "../providers/email-provider";

type Query = (sql: string, params?: unknown[]) => Promise<unknown[]>;

export class SequenceRepository {
  constructor(private query: Query = executeQuery) {}

  async dashboard(org:string){const rows=await this.query(`SELECT (SELECT COUNT(*) FROM review_assignments WHERE organization_id=$1 AND state<>'submitted') AS awaiting_review,(SELECT COUNT(*) FROM shortlist_decisions sd WHERE sd.organization_id=$1 AND sd.decision='shortlisted' AND NOT EXISTS(SELECT 1 FROM outreach_threads t WHERE t.organization_id=$1 AND t.candidate_id=sd.candidate_id AND t.position_id=sd.position_id)) AS decisions_pending,(SELECT COUNT(*) FROM sequence_enrollments WHERE organization_id=$1 AND status='scheduled' AND next_run_at<=CURRENT_TIMESTAMP) AS outreach_due,(SELECT COUNT(*) FROM outreach_threads WHERE organization_id=$1 AND status='replied') AS candidate_replies,(SELECT COUNT(*) FROM outreach_threads WHERE organization_id=$1 AND purpose='missing_information' AND status NOT IN('replied','completed','bounced','opt_out')) AS missing_information,(SELECT COUNT(*) FROM applications WHERE organization_id=$1 AND stage IN('under_review','needs_information')) AS stalled_applications`,[org]) as Record<string,unknown>[];return rows[0]??{}}

  async createAndEnroll(org: string, actor: string, input: {threadId:string;name:string;delayBusinessDays:number;subject:string;body:string}) {
    const thread = (await this.query(`SELECT t.*,a.stage FROM outreach_threads t LEFT JOIN applications a ON a.id=t.application_id AND a.organization_id=t.organization_id WHERE t.organization_id=$1 AND t.id=$2`, [org,input.threadId]))[0] as Record<string,unknown>|undefined;
    if (!thread) throw new Error("Outreach thread not found.");
    if (["replied","bounced","opt_out","paused","completed"].includes(String(thread.status))) throw new Error("Follow-ups cannot start after a reply or stop event.");
    const sequenceId=crypto.randomUUID(), stepId=crypto.randomUUID(), enrollmentId=crypto.randomUUID();
    const scheduled=nextBusinessHour(new Date(),input.delayBusinessDays);
    await this.query(`WITH s AS(INSERT INTO outreach_sequences(id,organization_id,name,purpose,status,business_timezone,max_attempts,created_by_id,approved_by_id,approved_at)VALUES($1,$2,$3,(SELECT purpose FROM outreach_threads WHERE organization_id=$2 AND id=$4),'approved','Asia/Kolkata',1,$5,$5,CURRENT_TIMESTAMP)),st AS(INSERT INTO outreach_steps(id,organization_id,sequence_id,step_order,delay_business_days,subject,body,status)VALUES($6,$2,$1,1,$7,$8,$9,'approved')),e AS(INSERT INTO sequence_enrollments(id,organization_id,sequence_id,thread_id,status,next_run_at,created_by_id)VALUES($10,$2,$1,$4,'scheduled',$11,$5))INSERT INTO audit_events(id,organization_id,actor_user_id,action,subject_type,subject_id,metadata)VALUES($12,$2,$5,'outreach.sequence_enrolled','sequence_enrollment',$10,json_build_object('next_run_at',$11::TEXT,'business_timezone','Asia/Kolkata','max_attempts',1))`,[sequenceId,org,input.name,input.threadId,actor,stepId,input.delayBusinessDays,input.subject,input.body,enrollmentId,scheduled.toISOString(),crypto.randomUUID()]);
    await queue.enqueue('send-outreach-followup',{organizationId:org,enrollmentId},{runAt:scheduled,maxAttempts:3,jobKey:`outreach-followup:${enrollmentId}`});
    return enrollmentId;
  }

  async deliver(org:string,enrollmentId:string){const rows=await this.query(`SELECT e.*,st.subject,st.body,t.candidate_id,t.status AS thread_status,ci.normalized_value AS candidate_email FROM sequence_enrollments e JOIN outreach_steps st ON st.organization_id=e.organization_id AND st.sequence_id=e.sequence_id AND st.step_order=e.current_step JOIN outreach_threads t ON t.organization_id=e.organization_id AND t.id=e.thread_id LEFT JOIN candidate_identities ci ON ci.organization_id=t.organization_id AND ci.candidate_id=t.candidate_id AND ci.identity_type='email' WHERE e.organization_id=$1 AND e.id=$2 AND e.status='scheduled' AND e.next_run_at<=CURRENT_TIMESTAMP AND t.status NOT IN('replied','bounced','opt_out','paused','completed') AND NOT EXISTS(SELECT 1 FROM opt_outs o WHERE o.organization_id=e.organization_id AND o.candidate_id=t.candidate_id AND o.channel='email')`,[org,enrollmentId]) as Record<string,unknown>[];const row=rows[0];if(!row){await this.query(`UPDATE sequence_enrollments SET status='stopped',stop_reason='stop_condition',stopped_at=CURRENT_TIMESTAMP,updated_at=CURRENT_TIMESTAMP WHERE organization_id=$1 AND id=$2 AND status='scheduled'`,[org,enrollmentId]);return}if(!row.candidate_email)throw new Error('Candidate has no source-backed email address.');const messageId=crypto.randomUUID();const result=await getEmailProvider().send({to:String(row.candidate_email),subject:String(row.subject),html:String(row.body).replaceAll('\n','<br>'),idempotencyKey:`sequence:${enrollmentId}:step:${row.current_step}`});await this.query(`WITH m AS(INSERT INTO outreach_messages(id,organization_id,thread_id,direction,subject,body,status,approval_version,approved_by_id,approved_at,provider,provider_message_id,idempotency_key,sent_at)VALUES($1,$2,$3,'outbound',$4,$5,$6,1,$7,CURRENT_TIMESTAMP,$8,$9,$10,CURRENT_TIMESTAMP)),e AS(UPDATE sequence_enrollments SET status='completed',attempts=attempts+1,stopped_at=CURRENT_TIMESTAMP,updated_at=CURRENT_TIMESTAMP WHERE organization_id=$2 AND id=$11)INSERT INTO audit_events(id,organization_id,actor_user_id,action,subject_type,subject_id,metadata)VALUES($12,$2,$7,'outreach.followup_sent','outreach_message',$1,json_build_object('provider',$8::TEXT,'simulated',$6::TEXT='simulated','enrollment_id',$11::TEXT))`,[messageId,org,row.thread_id,row.subject,row.body,result.status,row.created_by_id,result.provider,result.providerMessageId,`sequence:${enrollmentId}:step:${row.current_step}`,enrollmentId,crypto.randomUUID()])}

  async pause(org:string,actor:string,enrollmentId:string){await this.stop(org,actor,enrollmentId,"paused","outreach.sequence_paused")}

  private async stop(org:string,actor:string,id:string,status:string,action:string){const rows=await this.query(`WITH e AS(UPDATE sequence_enrollments SET status=$3,stop_reason=$3,stopped_at=CURRENT_TIMESTAMP,updated_at=CURRENT_TIMESTAMP WHERE organization_id=$1 AND id=$2 AND status='scheduled' RETURNING id)INSERT INTO audit_events(id,organization_id,actor_user_id,action,subject_type,subject_id,metadata)SELECT $4,$1,$5,$6,'sequence_enrollment',$2,json_build_object('reason',$3::TEXT)FROM e RETURNING id`,[org,id,status,crypto.randomUUID(),actor,action]);if(!rows[0])throw new Error("Only a scheduled sequence can be paused.")}

  async advance(org:string,actor:string,input:{threadId:string;rationale:string}){
    const context=(await this.query(`SELECT t.candidate_id,t.position_id,t.application_id,t.status,a.stage AS application_stage,sd.id AS decision_id,sd.candidate_evaluation_id,ce.rubric_id,ce.rubric_version,ce.evidence_snapshot FROM outreach_threads t JOIN applications a ON a.id=t.application_id AND a.organization_id=t.organization_id JOIN shortlist_decisions sd ON sd.organization_id=t.organization_id AND sd.candidate_id=t.candidate_id AND sd.position_id=t.position_id AND sd.decision='shortlisted' JOIN candidate_evaluations ce ON ce.id=sd.candidate_evaluation_id AND ce.organization_id=sd.organization_id WHERE t.organization_id=$1 AND t.id=$2 AND t.status='replied' ORDER BY sd.decided_at DESC LIMIT 1`,[org,input.threadId]))[0] as Record<string,unknown>|undefined;
    if(!context?.application_id)throw new Error("A candidate reply, shortlist decision, and application are required.");
    const snapshotId=crypto.randomUUID(),transitionId=crypto.randomUUID();
    await this.query(`WITH a AS(UPDATE applications SET stage='recruiter_screening' WHERE organization_id=$1 AND id=$2 AND stage IN('shortlisted','contacted','interested','needs_information') RETURNING id),e AS(UPDATE sequence_enrollments SET status='stopped',stop_reason='pipeline_advancement',stopped_at=CURRENT_TIMESTAMP,updated_at=CURRENT_TIMESTAMP WHERE organization_id=$1 AND thread_id=$3 AND status='scheduled'),s AS(INSERT INTO pipeline_handoff_snapshots(id,organization_id,application_id,candidate_id,position_id,shortlist_decision_id,candidate_evaluation_id,rubric_id,rubric_version,evidence_snapshot,response_thread_id,rationale,advanced_by_id)SELECT $4,$1,$2,$5,$6,$7,$8,$9,$10,$11::JSON,$3,$12,$13 FROM a),p AS(INSERT INTO pipeline_stage_transitions(id,organization_id,application_id,from_stage,to_stage,actor_user_id,rationale,snapshot_id)SELECT $14,$1,$2,$16,'recruiter_screening',$13,$12,$4 FROM a)INSERT INTO audit_events(id,organization_id,actor_user_id,action,subject_type,subject_id,metadata)SELECT $15,$1,$13,'pipeline.recruiter_screening','application',$2,json_build_object('snapshot_id',$4::TEXT,'human_action',true) FROM a RETURNING id`,[org,context.application_id,input.threadId,snapshotId,context.candidate_id,context.position_id,context.decision_id,context.candidate_evaluation_id,context.rubric_id,context.rubric_version,JSON.stringify(context.evidence_snapshot),input.rationale,actor,transitionId,crypto.randomUUID(),context.application_stage]);
  }
}
