'use server';
import { revalidatePath } from 'next/cache';
import { requireCurrentAccess } from '@/lib/auth/session';
import { AssignReviewerInputSchema, ReviewCommentInputSchema, ShortlistDecisionInputSchema, SubmitReviewInputSchema } from '@/features/panel-reviews/schemas/panel-review';
import { PanelReviewRepository } from '@/features/panel-reviews/repositories/panel-review-repository';

export async function assignReviewer(formData:FormData){const access=await requireCurrentAccess('positions:manage');const input=AssignReviewerInputSchema.parse({evaluationId:formData.get('evaluationId'),reviewerMemberId:formData.get('reviewerMemberId')});await new PanelReviewRepository().assign(access.organization.id,input.evaluationId,input.reviewerMemberId,access.userId);revalidatePath(`/reviews/${input.evaluationId}`);revalidatePath('/reviews');}
export async function submitPanelReview(formData:FormData){const access=await requireCurrentAccess('reviews:submit');const input=SubmitReviewInputSchema.parse({assignmentId:formData.get('assignmentId'),evaluationId:formData.get('evaluationId'),recommendation:formData.get('recommendation'),summary:formData.get('summary')});await new PanelReviewRepository().submit(access.organization.id,access.membership.id,access.userId,input);revalidatePath(`/reviews/${input.evaluationId}`);revalidatePath('/reviews');}
export async function addReviewComment(formData:FormData){const access=await requireCurrentAccess('reviews:submit');const input=ReviewCommentInputSchema.parse({evaluationId:formData.get('evaluationId'),criterionId:formData.get('criterionId')||undefined,body:formData.get('body')});await new PanelReviewRepository().comment(access.organization.id,access.membership.id,access.userId,input);revalidatePath(`/reviews/${input.evaluationId}`);}
export async function recordShortlistDecision(formData:FormData){const access=await requireCurrentAccess('shortlist:decide');const input=ShortlistDecisionInputSchema.parse({evaluationId:formData.get('evaluationId'),decision:formData.get('decision'),rationale:formData.get('rationale')});await new PanelReviewRepository().decide(access.organization.id,access.userId,input);revalidatePath(`/reviews/${input.evaluationId}`);revalidatePath('/reviews');revalidatePath('/candidates');}
